# Generated by Django 4.1.6 on 2023-02-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Building_name_And_RoomNumber',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
