# Generated by Django 4.1.6 on 2023-02-23 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0003_user_affliated_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Resume_profile',
            field=models.FileField(blank=True, null=True, upload_to='students/Resume/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
