# Generated by Django 4.1.6 on 2023-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0004_alter_user_resume_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(blank=True, max_length=225, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('images', models.ImageField(upload_to='')),
                ('created_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
