# Generated by Django 4.1.6 on 2023-02-14 08:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, choices=[('Dc', 'Data Collection'), ('sl', 'Selection'), ('pl', 'Placement')], max_length=5, null=True)),
                ('Creation_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Creator_note', models.TextField(default='')),
                ('expire_date_time', models.DateTimeField()),
                ('Originator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Visitng_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company_module.visiting_company_record')),
            ],
        ),
        migrations.CreateModel(
            name='ViewdBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_module.form')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseFromUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_Response', models.BooleanField(default=False)),
                ('Form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_module.form')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Form_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('UA', 'User Acceptance'), ('E', 'Extract')], max_length=3, null=True)),
                ('Text_q', models.TextField(default='')),
                ('Extract_from', models.TextField(blank=True, default='[]')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_module.form')),
            ],
        ),
        migrations.CreateModel(
            name='Additional_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.TextField(blank=True, null=True)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_module.questions')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_module.form')),
                ('form_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='form_module.responsefromuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response_To_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_Type', models.CharField(blank=True, choices=[('placed', 'placed'), ('selected', 'selected')], max_length=20, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='students/offerletter/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('Form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_module.form')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('Form_id', 'User')},
            },
        ),
    ]
