# Generated by Django 4.1.6 on 2023-02-27 08:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditon_1', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='avg of all sem required', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('conditon_2', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='10 percentage ', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('conditon_3', models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='12 percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_module.form')),
            ],
        ),
    ]
