# Generated by Django 4.1.6 on 2023-02-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_module', '0002_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditions',
            name='conditon_4',
            field=models.BooleanField(default=False, help_text='live kt not allowed'),
        ),
        migrations.AddField(
            model_name='conditions',
            name='conditon_5',
            field=models.BooleanField(default=False, help_text='Dead kt not allowed'),
        ),
    ]
