# Generated by Django 4.1.6 on 2023-02-27 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_module', '0003_conditions_conditon_4_conditions_conditon_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditions',
            name='form',
        ),
        migrations.AddField(
            model_name='form',
            name='conditions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form_module.conditions'),
        ),
    ]
