# Generated by Django 4.1.6 on 2023-03-18 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_module', '0001_initial'),
        ('form_module', '0004_remove_conditions_form_form_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Visitng_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_module.visiting_company_record'),
        ),
    ]
