# Generated by Django 4.1.6 on 2023-04-05 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_module', '0005_alter_form_visitng_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conditions',
            name='conditon_2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='10 percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
