# Generated by Django 4.1.6 on 2023-02-14 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specific_User_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_module.department')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_module.form')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Department_related_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department_module.department')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_module.form')),
            ],
        ),
    ]
